@base_url=http://localhost:8081
# @name auth
GET {{base_url}}/tokenz

###
@token = {{auth.response.body.$.token}}

###
POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}
TransactionID: x123

{
    "text": "sleep"
}